export const ERROR_TYPES = {
  CREDENTIALS_SIGN_IN: 'CredentialsSignin',
  CALLBACK_ROUTE_ERROR: 'CallbackRouteError',
};

export const ERROR_STATUS = {
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
