name: Build Android APK with Expo

on:
  push:
    tags:
      - "v*.*.*"
    branches: ["main"]
    paths:
      - "practice-one/**"
      - ".github/workflows/build-expo.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "practice-one/**"
      - ".github/workflows/build-expo.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      API_URL: ${{ vars.API_URL }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_PUBLIC_ENABLE_STORYBOOK: ${{ vars.EXPO_PUBLIC_ENABLE_STORYBOOK }}
    defaults:
      run:
        working-directory: ./practice-one
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up Node.js and install dependencies
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ./practice-one/yarn.lock

      - name: install app
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # Set environment variables
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_EXPO_PUBLIC_API_URL: ${{ vars.API_URL }}
          envkey_EXPO_PUBLIC_ENABLE_STORYBOOK: ${{ vars.EXPO_PUBLIC_ENABLE_STORYBOOK }}
          directory: ./practice-one
          file_name: .env

      # Setup Expo and EAS with EXPO_TOKEN secret
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android app
        run: eas build --platform android --profile production --local --output ${{ github.workspace }}/TradlyStore.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-apk
          path: ${{ github.workspace }}/TradlyStore.apk

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Expo APK
        uses: actions/download-artifact@v4
        with:
          name: expo-apk
          path: dist

      # Generate release notes and create a GitHub release
      - name: Generate CHANGELOG
        run: |
          echo "# Release Notes for TradlyStore ${{ github.ref_name }}" > dist/CHANGELOG.md
          echo "- The Expo and CLI APKs of TradlyStore" >> dist/CHANGELOG.md

      - name: Create GitHub Release with APKs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.apk
          body_path: dist/CHANGELOG.md
