name: Build Android APK with Expo

on:
  push:
    tags:
      - "expo-v*.*.*"
    branches: ["main"]
    paths:
      - "practice-one/**"
      - ".github/workflows/build-expo.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "practice-one/**"
      - ".github/workflows/build-expo.yml"
  workflow_dispatch:
    inputs:
      runsOn:
        description: "Choose GitHub runner"
        required: true
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - macos-latest
      environment:
        description: "Select the environment"
        type: environment
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runsOn || 'ubuntu-latest' }}
    environment: ${{ inputs.environment || 'development' }}
    env:
      API_URL: ${{ vars.API_URL }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_PUBLIC_ENABLE_STORYBOOK: ${{ vars.EXPO_PUBLIC_ENABLE_STORYBOOK }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    defaults:
      run:
        working-directory: ./practice-one
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Check the actual runner OS
      - name: Show actual runner OS
        run: echo "ACTUAL RUNNER OS '${{ runner.os }}'"

      # Check environment variables
      - name: Check environment variables
        run: |
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

      # Set up Node.js and install dependencies
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ./practice-one/yarn.lock

      - name: install app
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # Set environment variables
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_EXPO_PUBLIC_API_URL: ${{ vars.API_URL }}
          envkey_EXPO_PUBLIC_ENABLE_STORYBOOK: ${{ vars.EXPO_PUBLIC_ENABLE_STORYBOOK }}
          directory: ./practice-one
          file_name: .env

      # Run the build and tests
      - name: Run Tests
        run: yarn test

      # Setup Expo and EAS with EXPO_TOKEN secret
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android app
        run: eas build --platform android --profile production --local --output ${{ github.workspace }}/TradlyStore.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-apk
          path: ${{ github.workspace }}/TradlyStore.apk

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Expo APK
        uses: actions/download-artifact@v4
        with:
          name: expo-apk
          path: dist

      # Generate release notes and create a GitHub release
      - name: Generate CHANGELOG
        run: |
          # echo "# Release Notes for TradlyStore Expo ${{ github.ref_name }}" > dist/CHANGELOG.md
          echo "- The Expo APK of TradlyStore" >> dist/CHANGELOG.md

      - name: Create GitHub Release with APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.apk"
          tag: ${{ github.ref_name }}
          bodyFile: dist/CHANGELOG.md
