name: Build Android APK with CLI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build"
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./TradlyStore
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ./TradlyStore/yarn.lock

      - name: install app
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant Gradlew permission
        if: runner.os != 'Windows'
        run: chmod +x android/gradlew

      - name: Grant Gradlew permission in Windows
        if: runner.os == 'Windows'
        run: icacls android\gradlew /grant Everyone:"(RX)"
        shell: powershell

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_URL: ${{ vars.API_URL }}
          envkey_UPLOAD_IMAGE_URL: ${{ vars.UPLOAD_IMAGE_URL }}
          envkey_KEY_UPLOAD_IMAGE: ${{ secrets.KEY_UPLOAD_IMAGE }}
          directory: ./TradlyStore
          file_name: .env
