name: Build Android APK with CLI

on:
  push:
    tags:
      - "cli-v*.*.*"
    branches: ["main"]
    paths:
      - "TradlyStore/**"
      - ".github/workflows/build-cli.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "TradlyStore/**"
      - ".github/workflows/build-cli.yml"

  workflow_dispatch:
    inputs:
      runsOn:
        description: "Choose GitHub runner"
        required: true
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      environment:
        description: "Select the environment"
        type: environment
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'development' }}
    env:
      API_URL: ${{ vars.API_URL }}
      UPLOAD_IMAGE_URL: ${{ vars.UPLOAD_IMAGE_URL }}
      KEY_UPLOAD_IMAGE: ${{ secrets.KEY_UPLOAD_IMAGE }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    defaults:
      run:
        working-directory: ./TradlyStore
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Test environment variables
      - name: Check environment variables
        run: |
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

      # Set up Node.js and install dependencies
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ./TradlyStore/yarn.lock

      - name: install app
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant Gradlew permission
        if: runner.os != 'Windows'
        run: chmod +x android/gradlew

      # Set environment variables
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_URL: ${{ vars.API_URL }}
          envkey_UPLOAD_IMAGE_URL: ${{ vars.UPLOAD_IMAGE_URL }}
          envkey_KEY_UPLOAD_IMAGE: ${{ secrets.KEY_UPLOAD_IMAGE }}
          envkey_MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          envkey_MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.ALIAS }}
          envkey_MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          directory: ./TradlyStore
          file_name: .env

      # Run the build and tests
      - name: Run Tests
        run: yarn test

      - name: Build apk
        run: yarn build:apk

      # Sign and upload the APK
      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > ./TradlyStoreandroid/app/your_key_name.keystore

      - name: Rename signed APK
        run: |
          mv "./TradlyStore/android/app/build/outputs/apk/release/app-release.apk" "${{ github.workspace }}/TradlyStore.apk"

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: cli-apk
          path: ${{ github.workspace }}/TradlyStore.apk
          retention-days: 3

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download CLI APK
        uses: actions/download-artifact@v4
        with:
          name: cli-apk
          path: dist

      # Generate release notes and create a GitHub release
      - name: Generate CHANGELOG
        run: |
          echo "# Release Notes for TradlyStore CLI ${{ github.ref_name }}" > dist/CHANGELOG.md
          echo "- The CLI APK TradlyStore" >> dist/CHANGELOG.md

      - name: Create GitHub Release with APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.apk"
          tag: ${{ github.ref_name }}
          bodyFile: dist/CHANGELOG.md
