name: Build Android APK with CLI

on:
  push:
    tags:
      - "cli-v*.*.*"
    branches: ["main"]
    paths:
      - "TradlyStore/**"
      - ".github/workflows/build-cli.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "TradlyStore/**"
      - ".github/workflows/build-cli.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      API_URL: ${{ vars.API_URL }}
      UPLOAD_IMAGE_URL: ${{ vars.UPLOAD_IMAGE_URL }}
      KEY_UPLOAD_IMAGE: ${{ secrets.KEY_UPLOAD_IMAGE }}
    defaults:
      run:
        working-directory: ./TradlyStore
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up Node.js and install dependencies
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ./TradlyStore/yarn.lock

      - name: install app
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant Gradlew permission
        if: runner.os != 'Windows'
        run: chmod +x android/gradlew

      # Set environment variables
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_URL: ${{ vars.API_URL }}
          envkey_UPLOAD_IMAGE_URL: ${{ vars.UPLOAD_IMAGE_URL }}
          envkey_KEY_UPLOAD_IMAGE: ${{ secrets.KEY_UPLOAD_IMAGE }}
          directory: ./TradlyStore
          file_name: .env

      - name: Build apk
        run: yarn build:apk

      # Sign and upload the APK
      - name: Sign app APK
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: TradlyStore/android/app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: Debug signed file path
        run: echo "Signed file path - ${{ steps.sign_app.outputs.signedFile }}"

      - name: Rename signed APK
        run: |
          mv "${{ steps.sign_app.outputs.signedFile }}" "${{ github.workspace }}/TradlyStore.apk"

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: cli-apk
          path: ${{ github.workspace }}/TradlyStore.apk
          retention-days: 3

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download CLI APK
        uses: actions/download-artifact@v4
        with:
          name: cli-apk
          path: dist

      - name: List files in dist
        run: ls -la dist

      # Generate release notes and create a GitHub release
      - name: Generate CHANGELOG
        run: |
          echo "# Release Notes for TradlyStore CLI ${{ github.ref_name }}" > dist/CHANGELOG.md
          echo "- The CLI APK TradlyStore" >> dist/CHANGELOG.md

      - name: Create GitHub Release with APKs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.apk
          body_path: dist/CHANGELOG.md
