name: Release APKs

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download CLI APK
        uses: actions/download-artifact@v4
        with:
          name: cli-apk
          path: dist

      # - name: Download Expo APK
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: expo-apk
      #     path: dist

      - name: Generate CHANGELOG
        run: |
          echo "# Release Notes for ${{ github.ref_name }}" > dist/CHANGELOG.md
          echo "- CLI APK and Expo APK included" >> dist/CHANGELOG.md

      - name: Create GitHub Release with APKs
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/*.apk
          body_path: dist/CHANGELOG.md
